name: mrchess
version: 1.0.0+1
publish_to: none
description: A new Flutter project for devfest 2023
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  chat_gpt_sdk: ^2.2.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 1.0.0
  we_slide: 2.4.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito/Nunito-Regular.ttf

